name: building-and-deployment-qa

on:
  push:
    branches:
      - main
      - qa
      - feature/*
      - feature
      - bugfix/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8.0_281
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.412
          distribution: 'adopt'
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test


